version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #links:
      #- app

  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
