version: '3.3'

services:
  lb_back:
    container_name: lb_back
    image: nginx:1.15.12
    ports:
      - "8000:8000"
    volumes:
      - ./nginx_back/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_back1
      - app_back2

  app_back1:
    container_name: app_back1
    build:
      context: ./app_back
      dockerfile: ./Dockerfile
    image: app_back1
    ports:
      - "8081:8080"
    depends_on:
      - db
    tty: true

  app_back2:
    container_name: app_back2
    build:
      context: ./app_back
      dockerfile: ./Dockerfile
    image: app_back2
    ports:
      - "8081:8080"
    depends_on:
      - db
    tty: true

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/var/lib/mysql mysql
    ports:
      - "3306:3306"
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike_championship
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
    command: mysql -uroot -proot -e "FLUSH PRIVILEGES;"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 6080:8080
