version: '3.2'

services:
  nginx:
    image: nginx:1.15.12
    ports:
      - "80:80"
    #volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #links:
      #- app1

  app1:
    depends_on:
      - db
    image: tomcat:8.0
    volumes:
      - ./app/src:/app
    ports:
      - "8081:8080"

  app2:
    depends_on:
      - db
    image: tomcat:8.0
    volumes:
      - ./app/src:/app
    ports:
      - "8082:8080"

  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike_championship
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
